
/****** Object:  FullTextCatalog [Keyword]    Script Date: 2/29/2016 4:04:03 PM ******/
IF EXISTS (SELECT 1 FROM sys.fulltext_catalogs WHERE [name] = 'Keyword')
	PRINT 'Catalog exists'
DROP FULLTEXT CATALOG [Keyword]
GO

/****** Object:  FullTextCatalog [Keyword]    Script Date: 2/29/2016 4:04:03 PM ******/
CREATE FULLTEXT CATALOG [Keyword]WITH ACCENT_SENSITIVITY = ON

GO



/****** Object:  FullTextStopList freetext    Script Date: 2/29/2016 4:05:57 PM ******/
DROP FULLTEXT STOPLIST [freetext];

GO

/****** Object:  FullTextStopList freetext    Script Date: 2/29/2016 4:05:57 PM ******/
CREATE FULLTEXT STOPLIST [freetext]
;
ALTER FULLTEXT STOPLIST [freetext] ADD '!' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '!' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '#' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '#' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '$' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '$' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '%' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '%' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '&' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '&' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '(' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '(' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD ')' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD ')' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '*' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '*' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '+' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '+' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '-' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '-' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '/' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '/' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '0' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '0' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '1' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '1' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '2' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '2' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '3' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '3' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '4' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '4' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '5' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '5' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '6' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '6' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '7' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '7' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '8' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '8' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '9' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '9' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD ':' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD ':' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD ';' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD ';' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '<' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '<' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '=' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '=' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '>' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '>' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '?' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '?' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '@' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '@' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '[' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '[' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD ']' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD ']' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '_' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '_' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'a' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'a' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'also' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'also' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'am' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'am' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'an' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'an' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'and' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'and' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'any' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'any' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'are' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'are' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'as' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'as' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'b' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'b' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'c' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'c' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'd' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'd' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'e' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'e' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'f' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'f' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'g' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'g' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'h' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'h' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'i' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'i' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'is' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'is' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'j' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'j' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'k' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'k' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'l' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'l' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'm' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'm' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'n' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'n' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'o' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'o' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'p' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'p' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'q' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'q' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'r' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'r' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 's' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 's' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 't' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 't' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'u' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'u' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'v' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'v' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'w' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'w' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'was' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'was' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'were' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'were' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'x' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'x' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'y' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'y' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD 'z' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD 'z' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '{' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '{' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '|' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '|' LANGUAGE 'English';
ALTER FULLTEXT STOPLIST [freetext] ADD '}' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST [freetext] ADD '}' LANGUAGE 'English';

GO



